version: '3.6'
services:
  postgres:
    image: postgres:11-alpine
  django:
    image: django
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/code
      - static:/static
      - media:/media
volumes:
  static:
    driver: local
  media:
    driver: local