# Generated by Django 2.2.3 on 2019-07-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rxcui', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('synonym', models.CharField(blank=True, max_length=250)),
                ('language', models.CharField(max_length=10)),
                ('suppress', models.CharField(max_length=10)),
                ('umlscui', models.CharField(max_length=10)),
            ],
        ),
    ]
