# Generated by Django 2.2.3 on 2019-07-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('severity', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=250)),
                ('drugs', models.ManyToManyField(related_name='interactions', to='drug.Drug')),
            ],
        ),
    ]
